site_name: MUI Lightning Components
repo_url: https://github.com/lightningkite/mui-lightning-components
nav:
  - Home: index.md
  - Guide:
      - Getting Started: guide/getting-started.md
      - Components:
          - Rest Data Table: guide/rest-data-table.md
          - Rest Autocomplete: guide/rest-autocomplete.md
          - Hover Help: guide/hover-help.md
      - Functions:
          - Formik Helpers: guide/formik-helpers.md
          - Make Search Conditions: guide/make-search-conditions.md
      - Hooks:
          - useThrottle: guide/use-throttle.md
  - Contributing:
      - Library: contributing/contributing-library.md
      - Docs: contributing/contributing-docs.md
theme:
  name: material
  palette:
    primary: blue
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
extra_css:
  - style.css
